# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
nd_height = np.array(height)
nd_width = np.array(weight)
bmi_calc  = nd_width / (nd_height**2) * 730
print("The BMI's are")
print(bmi_calc)



The BMI's are
[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [11]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#pass
def makeMatrix(low,high,shape = (3,3),data_type = float):
    if data_type == int:
        return(np.random.randint(low, high, size = shape))
    return(np.random.uniform(low,high, size= shape))

print(makeMatrix(1,10))
print(makeMatrix(1,10,data_type = int, shape=(5,6)))
print(makeMatrix(1,10, data_type = int))


[[4.94315155 8.74493927 7.90609076]
 [7.14191587 3.39482208 6.61250422]
 [5.25019604 6.57241479 8.19787891]]
[[3 6 4 6 4 8]
 [8 9 1 1 7 1]
 [4 7 8 3 5 9]
 [6 1 3 6 8 3]
 [7 6 7 4 2 2]]
[[3 1 9]
 [1 7 1]
 [1 1 1]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [16]:
import csv
import numpy as np

#Test to make sure you have the correct data
print(open('../day-1/files/redsox_2017_hitting.txt').readlines()[0:5])
print(open('../day-1/files/redsox_2018_hitting.txt').read())


['Rk,Pos,Name,Age,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB\n', '1,C,Christian Vazquez,26,99,345,324,43,94,18,2,5,32,7,2,17,64,.290,.330,.404,.735,91,131,14,3,0,1,0\n', '2,1B,Mitch Moreland,31,149,576,508,73,125,34,0,22,79,0,1,57,120,.246,.326,.443,.769,99,225,14,6,0,5,6\n', '3,2B,Dustin Pedroia,33,105,463,406,46,119,19,0,7,62,4,3,49,48,.293,.369,.392,.760,100,159,11,2,2,4,4\n', '4,SS,Xander Bogaerts,24,148,635,571,94,156,32,6,10,62,15,1,56,116,.273,.343,.403,.746,95,230,17,6,0,2,6\n']
Rk,Pos,Name,Age,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
1,C,Sandy Leon,29,89,288,265,30,47,12,0,5,22,1,0,15,75,.177,.232,.279,.511,37,74,6,4,3,1,0
2,1B,Mitch Moreland,32,124,459,404,57,99,23,4,15,68,2,0,50,102,.245,.325,.433,.758,102,175,12,0,0,5,2
3,2B,Eduardo Nunez,31,127,502,480,56,127,23,3,10,44,7,2,16,69,.265,.289,.388,.677,81,186,17,2,1,3,0
4,SS,Xander Bogaerts,25,136,580,513,72,148,45,3,23,103,8,2,55,102,.288,.360,.522,.883,

In [31]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def get_data(fileName, d = ',',data_type = float):
    data  = np.genfromtxt(fileName, delimiter = d, skip_header = 1,
                         usecols = np.arange(0,24), invalid_raise = False,
                         names = FIELDS, dtype = DATATYPES) 
    return data

seven = get_data('../day-1/files/redsox_2017_hitting.txt')["SLG"]
print("--2017 SLG--")
print( np.average(seven))
print( np.max(seven))
print( np.min(seven))
print( np.std(seven))
print( np.size(seven))


eight = get_data('../day-1/files/redsox_2018_hitting.txt')["SLG"]
print("--2018 SLG--")
print( np.max(eight))
print( np.min(eight))
print( np.std(eight))
print( np.size(eight))


print("----2017 minus 2018----")
print("Minimum =", np.min(seven) - np.min(eight))
print("Maximum =", np.max(seven) - np.max(eight))
print("Average =", np.average(seven) - np.average(eight))



--2017 SLG--
0.39334783
1.0
0.2
0.15283398
23
--2018 SLG--
0.64
0.091
0.13244301
20
----2017 minus 2018----
Minimum = 0.109000005
Maximum = 0.36
Average = 0.0058478415
